# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.1.1'] #['3.6.3', '4.1.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::testthat
            any::rcmdcheck
            any::remotes
            any::bookdown
            any::RcppEigen
            any::purrr
            any::tidyr
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual","--no-multiarch","--force"), error_on = "error")
        shell: Rscript {0}

      - name: Install SpatialSablefishAssessment
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/settings/tokens
        run: Rscript -e "devtools::install_github('Craig44/SpatialSablefishAssessment', dependencies = F, INSTALL_opts = '--no-multiarch')"
      - name: Run Tests
        run: Rscript -e 'devtools::test(stop_on_failure = T)'

      - name: Render Gitbook
        run: Rscript -e "bookdown::render_book(input = 'Gitbook')"
      - name: artifact Gitbook
        uses: actions/upload-artifact@v1
        with:
          name: _book
          path: GitBook/_book/
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/settings/tokens
       with:
          email: ${{ secrets.EMAIL }}               # must be a verified email
          build_dir: _book/                     # "_site/" by default
          branch: gh-pages      #
